# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6d106a9e6bcff2941129546d4df6e5db89d895056936d2f78eb6bb46a38ef92a9209c78b5f1ee3c28c741fb6c21a3a0d697bc33d69d37f77fa72398079aca9b

test:
  secret_key_base: 2bbb9df79214f2af4149f081322c7307a5f3c1c308654a7ccb009e4813d45a2666e5877d286337beba1838260fd970f379b18fca096aaad88fae71038d2636eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
